### ISSUE TITLE
NeoForge Compatibility

### ISSUE THREAD

**Issue by drakray** [gisellevonbingen-Minecraft/MineColonies_Compatibility#1]
Just saw this require Forge 47.2.0, could it be possible to make it compatible with Neoforge 47.1.105 please?
I tried just changing the requirement in mods.toml, and it booted, but I'm not sure if it will work long term

Thank you fir your good work :D

**Comment by gisellevonbingen** [comment]
Downgrade forge version dependency to 47.1.13.
Thanks for report.
