### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ZEUS-102** [gisellevonbingen-Minecraft/MineColonies_Compatibility#11]
I write through translator
I had an error and support advised me to contact you.
https://github.com/ldtteam/minecolonies/issues/9993

**Comment by gisellevonbingen** [comment]
I can't understand why this occurred.
Fixed the suspicious code and will release it soon.

**Comment by gisellevonbingen** [comment]
Ah, was archer hired at Barracks?
I found cause.
