### ISSUE TITLE
Multiple warehouses

### ISSUE THREAD

**Issue by Uh-21** [gisellevonbingen-Minecraft/MineColonies_Compatibility#18]
I can't connect several warehouses to the same AE2 system, any help? I use a quantum bridge to bring my system input/output. The fact is that I can connect 1 warehouse, but with a 2nd I can't, i select refresh but the block doesn't link. I tried using 1 terminal for both and 1 for each. None of these helped. So I can only "comunicate" with 1 warehouse in my hole colony.

1.19.2 (Forge) Using Applied Energistics 2

**Comment by gisellevonbingen** [comment]
Can you try to place 'ME Terminal for Colonist' at another location?
To easy link, attach that terminal at cable where above from floor.

**Comment by gisellevonbingen** [comment]
You also need to make that multiple warehouses do not have the same network connected.
Because the deliveryman searches for items for each warehouse, the items in the same network are count up repeatedly.
Or try use subnetwork.

**Comment by Uh-21** [comment]
how do I connect diferent networks? sorry for bad english (I naturally speak spanish)

**Comment by gisellevonbingen** [comment]
Just place link blocks in warehouse.
https://github.com/gisellevonbingen-Minecraft/MineColonies_Compatibility/wiki/Courier-%E2%80%90-Network-Storage
