### ISSUE TITLE
[Feature Request] compatibility with ewewukeks-musket-mod

### ISSUE THREAD

**Issue by AliTeo** [gisellevonbingen-Minecraft/MineColonies_Compatibility#23]
It only has one gun. A musket with and without a sword. Would appreciate it if possible

**Comment by lluminanoctis** [comment]
It has three guns actually, a musket, a musket with a bayonet (which are kind of separate) and a pistol. But yes, compatibility would be appreciated.

**Comment by gisellevonbingen** [comment]
OK i will do this.

**Comment by gisellevonbingen** [comment]
Done on 1.19.2-1.30 and 1.20.1-2.30 versions.
Thanks for idea.

**Comment by AliTeo** [comment]
> Done on 1.19.2-1.30 and 1.20.1-2.30 versions. Thanks for idea.

Thank you for your time
