### ISSUE TITLE
Crash with REI 

### ISSUE THREAD

**Issue by WenXin20** [gisellevonbingen-Minecraft/MineColonies_Compatibility#26]
```
Minecraft v1.20.1
Minecolonies Compat v2.24
REI v12.1.725
```

When searching in the REI Collapsible Groups screen, the game will crash. 
To get to this screen, go to `Settings -> List -> Collapsible Groups -> Configure -> "+" Button -> Select Entries`. 
And then when trying to search for an item, that is when it crashes
[Crash Report](https://gist.github.com/WenXin20/75c84a8d9605bf40ee6403235c1ff5bb)

![image](https://github.com/user-attachments/assets/8f99c2f6-2df9-4085-aafe-8d63dc538dad)

**Comment by gisellevonbingen** [comment]
Thanks for report. 👍 
Fixed version will release soon.

**Comment by WenXin20** [comment]
Thanks!

**Comment by gisellevonbingen** [comment]
Fixed on 1.20.1-2.25 version
