### ISSUE TITLE
Crash with [Let's Do] Vinery

### ISSUE THREAD

**Issue by niessenty** [gisellevonbingen-Minecraft/MineColonies_Compatibility#28]
I run into an error when adding this mod to a modpack that contains Vinery. I've attached the crash report, but here are the two areas:

```
java.lang.RuntimeException: null
    at net.minecraftforge.fml.DeferredWorkQueue.runTasks(DeferredWorkQueue.java:58)
```

```
java.lang.NoClassDefFoundError: net/satisfy/vinery/registry/ObjectRegistry
    at steve_gall.minecolonies_compatibility.module.common.vinery.AppleLeavesFruit.getId(AppleLeavesFruit.java:25)
```

[crash-2024-07-16_17.33.58-client.txt](https://github.com/user-attachments/files/16262429/crash-2024-07-16_17.33.58-client.txt)

**Comment by gisellevonbingen** [comment]
Please update Vinery.

**Comment by niessenty** [comment]
Having updated all the mods, there is now a clash with Geode+. Is there a version of this mod which will work, or is it incompatible with MC Compatability?

[crash-2024-07-17_10.57.21-client.txt](https://github.com/user-attachments/files/16263704/crash-2024-07-17_10.57.21-client.txt)
