### ISSUE TITLE
Request for compat work: More Mob Variants

### ISSUE THREAD

**Issue by AnyankaT** [gisellevonbingen-Minecraft/MineColonies_Compatibility#3]
Hi! I'm excited about your mod, making MC more compat with other mods.

We're running into an issue with the More Mob Variants mod for 1.20.1, in that the colonists have difficulty working with animal variants. The archers kill variant sheep and pigs as if they were hostile mobs, and the chicken herder won't kill variant chickens, although they will breed them.

Anything you'd be interested in adding to your mod?

**Comment by gisellevonbingen** [comment]
In fact, the Variants are just a variation of the rendering.
Functionally same with vanilla.
That is came from other cause.
