### ISSUE TITLE
Farmer's Cook not working

### ISSUE THREAD

**Issue by niessenty** [gisellevonbingen-Minecraft/MineColonies_Compatibility#30]
The farmer's cook doesn't see the heated cooking pot, and keeps asking me to place one. I have tried this on new worlds, as well as rebuilding the restaurant.

It does allow me to teach recipes, the cook just doesn't acknowledge that the heated pot is there.

Version 2.20, with Colonies version 1.603

MC 1.20.1

![Screenshot (621)](https://github.com/user-attachments/assets/bdb088a3-8ad0-4a4a-ba7f-6bba882c9461)

**Comment by gisellevonbingen** [comment]
It seems that Citizen AI's route finding algorithm was unable to find the route.
Would you like to place cooking pot in a different location?
Otherwise, don't place any blocks around the pot.

**Comment by niessenty** [comment]
I've just cleared out the area to test, and still seems not to work, unless I've not set the cook up properly?

![Screenshot (622)](https://github.com/user-attachments/assets/28c2b567-efac-4073-9d74-61a6fa03cf81)
![Screenshot (623)](https://github.com/user-attachments/assets/ccfd061f-6f5a-4914-95c9-a5a1b056d3ae)

**Comment by gisellevonbingen** [comment]
Huhh... what is theme you using?

**Comment by niessenty** [comment]
Medieval Spruce. That is AltCook building

**Comment by gisellevonbingen** [comment]
Then what is Tweaks addon version?

**Comment by niessenty** [comment]
Tweaks is 2.24

**Comment by gisellevonbingen** [comment]
Maybe that is cause.
Try to down Tweak version to 2.22.
Or update Compatibility to 2.24.

My suggestion is use latest verion of all addon and MineColonies.

**Comment by gisellevonbingen** [comment]
It works for me.
![image](https://github.com/user-attachments/assets/ba1964bd-3406-4cfd-9d21-771d2a6bdf55)
![image](https://github.com/user-attachments/assets/2b2c0c7b-4b1d-464a-9a3d-0a35c93afdda)

**Comment by niessenty** [comment]
Upgrading both to 2.24 seems to have fixed this
