### ISSUE TITLE
[Feature Request] Epic Fight compatability for the villagers and the raiders

### ISSUE THREAD

**Issue by stygal726** [gisellevonbingen-Minecraft/MineColonies_Compatibility#31]
this request is for the npc villagers and raiders in minecolonies to use epic fight animations included in the base mod as well as the movesets addons like rapier, weapons of minecraft, guandao moveset, etc. this would allow people that use epic fight as their main combat mod to not break immersion when the player is using the animations but their town gaurd or the raiders arent.

**Comment by gisellevonbingen** [comment]
MineColonies entity model is not compatible with Epic Fight.
It is too different to Minecraft vanilla model.
Sorry.
