### ISSUE TITLE
Please use officially supported channels for modifying the mod wherever possible, no mixins

### ISSUE THREAD

**Issue by Thodor12** [gisellevonbingen-Minecraft/MineColonies_Compatibility#35]
There are a load of things that this mod adds through the means of mixins which is not necessary at all.
Many things can be done with datapacks directly, or through opened API's on our mod:
- Water bucket filling does not need to exist, we actually have a PR open for that right now which is just a recipe
- Do not mixin into the AI code, create custom AI code classes
- Remove knights and rangers using axes and crossbows, we as developers want to make this ourselves, so just PR the official creation if you want it
- Farm crops are already supported if you implement the new crops system (by extending our crop block)
- Remove the mixin into JobEntry, there's no need to modify translation keys, just insert the proper translation key for the job name into your translation json
- Remove the custom tool type system, just PR into minecolonies what you're missing to customize this, the intention is that this system is already customizable through an interface
- Do not modify building module code through mixins, again this is possible by just hooking into the registry added event and modifying instances where needed from there

I have no problem with the majority of things you're trying to do, just implement them in a smarter way, mixins break too easily

**Comment by gisellevonbingen** [comment]
1. Water bucket filling does not need to exist, we actually have a PR open for that right now which is just a recipe
```
No, this is necessary for pickup fluid like lava into bucket.
```

2. Do not mixin into the AI code, create custom AI code classes
```
No, it can't implement it the way I intended.
Many methods are declared as 'private'.
```

3. Remove knights and rangers using axes and crossbows
```
No, please make it from MineColonies first, then I will remove it.
```

4. Farm crops are already supported.
```
No, i know the farmer can't support Farmer's Delight's tomato and Immersive Engineering's Hemp and more.
```

5. Remove the mixin into JobEntry.
```
No, I don't want 'com.' prefix at translation key.
```

6. Remove the custom tool type system.
```
No, MineColonies Tool API is too inconvenient and some methodes are accept only 'ToolType', not 'IToolType'.
And custom tool type systems is more flexiable for CustemRecipes and creating a Modpack.
```

7. Do not modify building module code through mixins.
```
No, it can't.
```
