### ISSUE TITLE
Network Storage - additional mods compatibility

### ISSUE THREAD

**Issue by Dragnier** [gisellevonbingen-Minecraft/MineColonies_Compatibility#36]
Occultism and Mekanism both have their own digital storage like Refined/AE2 and it would be nice to see added compatibility with them as well.

**Comment by gisellevonbingen** [comment]
Mekanism QIO is planned.

**Comment by Dragnier** [comment]
> Mekanism QIO is planned.

The fact that Occultism isn't already planned makes me sad... far more used than Mekanism QIO...

**Comment by gisellevonbingen** [comment]
indeed, i don't know Occultism well.
give me a time to i learn it.

**Comment by gisellevonbingen** [comment]
Sorry, Network Storage feature been removed.
