### ISSUE TITLE
[Let's Do] Bakery Compat (new mod version for Farm&Charm) not supported

### ISSUE THREAD

**Issue by ZambeNib** [gisellevonbingen-Minecraft/MineColonies_Compatibility#41]
There is a new [Let's Do] Bakery Compat edition that satisfy has released. 

It's currently breaking this mod due to a java error "[Render thread/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Caught exception during event RegisterEvent dispatch for modid minecolonies_compatibility
java.lang.NoSuchFieldError: STOVE_RECIPE_TYPE"

The original mod that is supported is here:
https://www.curseforge.com/minecraft/mc-mods/lets-do-bakery

The new Compat version for Farm&Charm:
https://www.curseforge.com/minecraft/mc-mods/lets-do-bakery-farm-charm-compat

**Comment by gisellevonbingen** [comment]
new version is not planned to support, please use legacy version for a while.

**Comment by gisellevonbingen** [comment]
[#29 ](29#issuecomment-2282372281)
