### ISSUE TITLE
Cookery stopped working

### ISSUE THREAD

**Issue by LucaFerrarezi** [gisellevonbingen-Minecraft/MineColonies_Compatibility#46]
![image](https://github.com/user-attachments/assets/d5729224-030b-44d1-a458-772f350349dc)
https://gist.github.com/LucaFerrarezi/019fdb584a35034df2c31098edb7437d
Stopped working after i have updated this mod, was working before update

**Comment by gisellevonbingen** [comment]
What does before version?
Did you update MineColonies too?

**Comment by gisellevonbingen** [comment]
Fixed at 1.20.1-2.38.
Thanks for report

**Comment by LucaFerrarezi** [comment]
thank you for fix it.

**Comment by Jkosio23** [comment]
Happening again in version 2.43

**Comment by Jkosio23** [comment]
Can't get a log atm bc it's happening on a server

**Comment by Jkosio23** [comment]
Additionally, it only happened once the upgrade to tier 2 finished
