### ISSUE TITLE
Domum Ornamentum custom crafting recipe is broken when connected to simple storage compatibility block

### ISSUE THREAD

**Issue by protoss4more** [gisellevonbingen-Minecraft/MineColonies_Compatibility#48]
Minecraft V1.20.1

relevant mods:

Minecolonies-1.20.1-1.1.647-beta
MineColonies_compatibility-1.20.1-2.39
Minecolonies_tweaks-1.20.1-2.40
SimpleStorageNetwork-1.20.1-1.10.0

Issue: Colonists will not recognize the colony has a custom recipe for domum ornamentum blocks (sawmills, stonemason, mechanic, etc.) when connected to the compatibility block. Instead the request will be redirected to the warehouse with the resolver being player.

steps to reproduce:

1. start a colony with a builder, a warehouse and a stonemason/sawmill.
2. hire a colonist on each of the buildings.
3. connect the warehouse to a compatibility block.
4. create a build request that requires a domum block.
5. create a custom recipe for that block.
6. get a clipboard and check the domum request. It should show you that the domum block is being requested from the warehouse and not from the stonemason/sawmill.
7. remove the compatanbility block and cancel the request from warehouse. This will now show that the request will be forwarded to the sawmill/stonemason correctly.

Note that some recipe might not have this issue:
![image](https://github.com/user-attachments/assets/412a4511-bb07-4aaf-8d9d-154417405b6a)
_* the Stripped Acacia panel is broken but Stripped Oak wood gate is not._

**Comment by gisellevonbingen** [comment]
Can you try again with Compatibility addon [1.20.1-2.40](https://legacy.curseforge.com/minecraft/mc-mods/minecolonies-compatibility/files/5682245) version please?

**Comment by protoss4more** [comment]
still seems broken in 1.20-2.40. But since you did remove this functionality, I guess I close this issue.
