### ISSUE TITLE
Crash When Using with ewewukek's Musket Mod

### ISSUE THREAD

**Issue by ddaodan** [gisellevonbingen-Minecraft/MineColonies_Compatibility#49]
I hired a Gunner, and my game crashed when he shot.
[crash-2024-09-16_01.46.57-server.txt](https://github.com/user-attachments/files/17006902/crash-2024-09-16_01.46.57-server.txt)

This is another crash report when I reproduced the bug:
[crash-2024-09-16_01.51.48-server.txt](https://github.com/user-attachments/files/17006929/crash-2024-09-16_01.51.48-server.txt)

**Comment by gisellevonbingen** [comment]
Fixed. Please use previous version of ewewukek's Musket Mod please until this mod be updated.
I will notice again when new version released, then you can use latest ewewukek's Musket Mod.
