### ISSUE TITLE
about rs compatibility

### ISSUE THREAD

**Issue by yan-mc** [gisellevonbingen-Minecraft/MineColonies_Compatibility#56]
Minecolonies-1.20.1-1.1.647-beta

MineColonies_compatibility-1.20.1-2.39

Minecolonies_tweaks-1.20.1-2.34

Refined Storage-1.12.4

There are no issues with the DO blocks reported on github in this release.

https://github.com/gisellevonbingen-Minecraft/MineColonies_Compatibility/issues/48

Hope you can restore RS compatibility.

In my tests, all DO blocks were able to request, synthesize, and feed normally.

But I found a problem. When tool-like items exist in rs, they cannot be directly requested. When they are used as synthetic materials, they can be shipped normally. I can only use the old version to test, because the new version seems to disable this feature.

**Comment by gisellevonbingen** [comment]
But latest version's minecolonies code are too dificult to add a rs compatibility.
I'm sorry about that.
