### ISSUE TITLE
"Unsupported Tool" when trying to select a cutting board recipe

### ISSUE THREAD

**Issue by adlingtont** [gisellevonbingen-Minecraft/MineColonies_Compatibility#6]
All cutting board recipes are greyed out when trying to teach them to the Farmer's Cook. The tool tip error states "unsupported tool"

**Comment by gisellevonbingen** [comment]
Can't reproduce.
Is that recipes are using knife right?
Please Version, Modlist

**Comment by adlingtont** [comment]
Versions:
MineColonies_Compatibility-1.19.2-1.8.jar
minecolonies-1.19.2-1.1.573-BETA.jar

Probably of note: I had to add the forge:tools/knives tag back to knives

Mods List: 

1.19.2 Lovely Two Pixels v1.0.jar
ad_astra-forge-1.19.2-1.12.7.jar
AdChimneys-1.19.2-9.1.16.0-build.1080.jar
advancementframes-1.19.2-2.0.0.jar
AdvancementPlaques-1.19.2-1.4.7.jar
AE2-Things-1.1.1.jar
AI-Improvements-1.19.2-0.5.2.jar
alloyed-1.19.2-v1.5a.jar
almostunified-forge-1.19.2-0.5.0.jar
angelblockrenewed-forge-1.0-1.19.jar
AngelRing2-1.19.2-2.1.7.jar
appliedenergistics2-forge-12.9.5.jar
architectury-6.5.85-forge.jar
ars_artifice-1.19.2-1.0.6.jar
ars_instrumentum-1.19.2-3.4.5.jar
ars_nouveau-1.19.2-3.17.10.jar
arsomega-1.19.2-3.1.1.jar
artifacts-1.19.2-5.0.4.jar
aureusslabs-0.0.1-1.19.jar
auto_third_person-forge-1.19.2-2.jar
AutoRegLib-1.8.2-55.jar
balm-forge-1.19.2-4.5.7.jar
BetterAdvancements-1.19.2-0.2.2.142.jar
betteranimalsplus-1.19.2-11.0.10-forge.jar
BetterAnimationsCollection-v4.0.5-1.19.2-Forge.jar
betterdays-1.19.2-3.1.0.4-FORGE.jar
bettervillage-forge-1.19.2-3.1.0.jar
BiomesOPlenty-1.19.2-17.1.1.162.jar
BlockRunner-v4.2.2-1.19.2-Forge.jar
blockui-1.19.2-1.0.140-BETA.jar
botarium-forge-1.19.2-1.8.2.jar
BrewinAndChewin-1.19-2.0.jar
brutalbosses-1.19.2-6.3.jar
BuildingWands-mc1.19.2-2.6.8-release-forge.jar
caelus-forge-1.19.2-3.0.0.6.jar
camps_castles_carriages-1.1.1.jar
cc-tweaked-1.19.2-1.101.3.jar
charmofundying-forge-6.2.1+1.19.2.jar
chipped-forge-1.19.2-2.1.5.jar
Chunky-1.3.38.jar
citadel-2.1.4-1.19.jar
cloth-config-8.3.103-forge.jar
cobblegenrandomizer-1.19.2-1.2.jar
collective-1.19.2-7.30.jar
Colony4ComputerCraft-1.19.2-2.3.4.jar
configured-2.1.1-1.19.2.jar
Controlling-forge-1.19.2-10.0+7.jar
convenientcurioscontainer-1.12-1.19.2.jar
CosmeticArmours - 1.20 - 1.19.2.jar
craftingstation-1.19.2-6.0.1.jar
craftingtweaks-forge-1.19.2-15.1.8.jar
CraftTweaker-forge-1.19.2-10.1.49.jar
Create Ore Additions 4.2.1.jar
create_central_kitchen-1.19.2-for-create-0.5.1.c-1.3.9.c.jar
create_crystal_clear-0.2.1-1.19.2.jar
Create_Deco_Casing_3.0.0_1.19.jar
create_enchantment_industry-1.19.2-for-create-0.5.1.c-1.2.6.jar
create_factory-0.0.2-1.19.2.jar
create_jetpack-forge-3.2.2.jar
create_mechanical_extruder-1.19.2-1.5.0.c-36.jar
create_misc_and_things_  1.19.2_3.0.jar
create-1.19.2-0.5.1.c.jar
createaddition-1.19.2-20230623a.jar
createastracompat-1.0.3-1.19.2.jar
createcafe-1.2.1-1.19.2.jar
create-confectionery1.19.2_v1.0.9.jar
createdeco-1.3.3-1.19.2.jar
createendertransmission-2.0.1.jar
creategoggles-1.19.2-0.5.5.c-[FORGE].jar
create-structures-0.1.0.jar
create-stuff-additions1.19.2_v2.0.3b.jar
CreateTweaker-1.19.2-3.0.0.6.jar
CreativeCore_FORGE_v2.9.3_mc1.19.2.jar
CTM-1.19.2-1.1.6+8.jar
Cucumber-1.19.2-6.0.6.jar
culturaldelights-1.19.2-0.15.4.jar
cupboard-1.19.2-1.7.jar
curios-forge-1.19.2-5.1.4.1.jar
curiouslanterns-1.19.2-1.3.3.jar
customvillagertrades-forge-19.24.0.jar
Decorative Blocks-forge-1.19.2-3.0.0.jar
Delightful-1.19.2-3.4.1.jar
DiagonalFences-v4.2.5-1.19.2-Forge.jar
dimdungeons-178-forge-1.19.0.jar
Display Case-forge-1.19-1.0.3.jar
DistantHorizons-2.0.1-a-1.19.2.jar
doapi-1.1.0b.jar
domum_ornamentum-1.19-1.0.146-BETA-universal.jar
DungeonCrawl-1.19-2.3.12.jar
DustrialDecor-1.3.3-1.19.2.jar
dynamicvillagertrades-1.2.3-forge-1.19.2.jar
elytraslot-forge-6.1.1+1.19.2.jar
embellishedenchanting-v1.3.4-1.19.2.jar
endrem_forge-5.2.1-R-1.19.X.jar
Engineers Delight 1.19.2 B.1.1.jar
engineersdecor-1.19.2-forge-1.3.28.jar
EnhancedVisuals_FORGE_v1.5.9_mc1.19.2.jar
EnigmaticLegacy-2.26.5.jar
ExNihiloAE-1.19.2-4.1.0.52-beta.jar
ExNihiloSequentia-1.19.2-4.1.0.55-beta.jar
expandability-7.0.0.jar
ExplorersCompass-1.19.2-1.3.0-forge.jar
extendedgears-2.1.0-1.19.2-0.5.1.c-forge.jar
extratrades-1.19.2-1.2.jar
fancytrinkets-1.19-2.1.4.jar
FarmersDelight-1.19.2-1.2.2.jar
FarmersRespite-1.19-2.0.jar
fastfooddelight-1.19-1.2.3.jar
FastFurnace-1.19.2-7.0.0.jar
FastLeafDecay-30.jar
Fastload-Reforged-8.2.1+1.19.2.jar
FastSuite-1.19.2-4.1.0.jar
FastWorkbench-1.19.2-7.1.3.jar
Festive_Delight_1.0_1.19.2.jar
FORGE - TARDIS Refined v1-1.19.2.jar
ForgeEndertech-1.19.2-10.0.6.1-build.0897.jar
FPS optimizer 1.19.2.jar
frozen_delight_1.3.2_forge_1.19.2.jar
frozenup-1.19.2-2.1.2-forge.jar
ftb-library-forge-1902.3.19-build.214.jar
ftb-ultimine-forge-1902.4.0-build.77.jar
geckolib-forge-1.19-3.1.40.jar
giacomos_automatable_cauldrons1.0.2-1.19.2.jar
giacomos_bookshelf1.3.3-1.19.2.jar
gpumemleakfix-1.19.2-1.6.jar
handcrafted-forge-1.19.2-2.0.6.jar
Hostile_Delight_0.2.2_1.19.2.jar
Iceberg-1.19.2-forge-1.1.4.jar
immersive_armors-1.5.5+1.19.2-forge.jar
immersive_paintings-0.6.0+1.19.2-forge.jar
ImmersiveEngineering-1.19.2-9.2.2-165.jar
InsaneLib-1.7.5-mc1.19.2.jar
inventorysorter-1.19.2-21.0.4.jar
iris-mc1.19.2-1.6.9.jar
ItalianDelight-1.19.2 1.5-MAR_FIX.jar
ItShallNotTick-1.0.11-build.35.jar
Jade-1.19.1-forge-8.8.1.jar
jeed-1.19.2-2.1.4.jar
jei-1.19.2-forge-11.6.0.1016.jar
jeimultiblocks-1.19.2-0.0.3.jar
JeiTweaker-forge-1.19.2-4.0.12.jar
journeymap-1.19.2-5.9.7-forge.jar
justenoughbreeding-forge-1.19.2-1.0.1.jar
JustEnoughProfessions-forge-1.19.2-2.0.2.jar
JustEnoughResources-1.19.2-1.2.2.200.jar
kotlinforforge-3.12.0-all.jar
kubejs-forge-1902.6.0-build.142.jar
kubejs-immersive-engineering-1902.2.2-build.40.jar
kubejs-mekanism-1902.1.4-build.11.jar
lasermod-1.19-1.0.1.jar
letsdo-vinery-forge-1.3.12b.jar
libraryferret-forge-1.19.2-4.0.0.jar
light-overlay-7.0.1-forge.jar
lightspeed-1.19.2-1.0.5.jar
maenchants-1.19.2-6.0.0.jar
majrusz-library-forge-1.19.2-7.0.5-backport.1.jar
majruszs-enchantments-forge-1.19.2-1.10.7-backport.1.jar
MaxHealthFix-Forge-1.19.2-8.0.2.jar
mcjtylib-1.19-7.2.5.jar
mcw-bridges-2.0.7-mc1.19.2forge.jar
mcw-fences-1.0.7-mc1.19.2forge.jar
mcw-paintings-1.0.4-mc1.19.2.jar
mcw-roofs-2.2.3-mc1.19.2forge.jar
mdg-forge-1.19.2.jar
medieval_paintings-1.19.2-7.0.jar
megacells-forge-1.5.3-1.19.2.jar
Mekanism-1.19.2-10.3.8.477.jar
MekanismAdditions-1.19.2-10.3.8.477.jar
MekanismGenerators-1.19.2-10.3.8.477.jar
MekanismTools-1.19.2-10.3.8.477.jar
MineColonies_Compatibility-1.19.2-1.8.jar
MineColonies_Tweaks-1.19.2-1.16.jar
minecolonies-1.19.2-1.1.573-BETA.jar
MOAdecor COOKERY 1.19.2.jar
MOAdecor SCIENCE 1.19.2.jar
MOAdecor TOYS 1.19.2.jar
modlist.txt
modlist-1.0.2.jar
moonlight-1.19.2-2.2.34-forge.jar
More Villager Trades 1.0.0 - 1.19.2.jar
morediscs-1.19.2-28-forge.jar
more-immersive-wires-1.19.2-1.0.2.jar
MouseTweaks-forge-mc1.19-2.23.jar
multipiston-1.19.2-1.2.21-ALPHA.jar
MysticalAgradditions-1.19.2-6.0.3.jar
MysticalAgriculture-1.19.2-6.0.11.jar
Nameless Trinkets-1.19.2-1.7.3.jar
naturalist-forge-3.0.3-1.19.2.jar
NaturesCompass-1.19.2-1.10.0-forge.jar
NekosEnchantedBooks-1.19-1.8.0.jar
NethersDelight-1.19-3.0.jar
nocube's_create_compact_exp_1.0.2_forge_1.19.2.jar
nocubes_create_compats_1.0.0_forge_1.19.2.jar
nocube's_farmers_compats_1.0.0_Forge_1.19.2.jar
OCD1.19.2-0.1_alpha.jar
oceansdelight-1.0.2-1.19.2.jar
octolib-1.19.2-0.3.jar
Patchouli-1.19.2-77.jar
pathforged-1.1.jar
Placebo-1.19.2-7.2.0.jar
PureDiscsRelic-v1.0.0-1.19.2-Forge.jar
PureDiscsTrailsTales-v1.0.0-1.19.2-Forge.jar
PureDiscsTrickyTrials-v1.0.0-1.19.2-Forge.jar
PuzzlesLib-v4.4.0-1.19.2-Forge.jar
Quark-3.4-405.jar
QuarkEngineering.jar
QuarkOddities-1.18.jar
radiantgear-forge-2.0.1+1.19.2.jar
relics-1.19.2-0.6.2.4.jar
remotes-2.0.1.jar
resourcefulconfig-forge-1.19.2-1.0.20.jar
resourcefullib-forge-1.19.2-1.1.24.jar
rhino-forge-1902.2.2-build.268.jar
rsgauges-1.19.2-forge-1.2.19.jar
rubidium-0.6.2b.jar
saturn-mc1.19.2-0.0.4.jar
seamless_loading_screen-1.19.2-4.0.2.jar
Shields+-1.3.2-mc1.19.2.jar
shutupexperimentalsettings-1.0.5.jar
signpost-1.19.2-2.01.0.jar
sliceanddice-forge-2.2.1.jar
smallships-forge-1.19.2-2.0.0-b1.2.jar
snowundertrees-1.19.2-1.3.1.jar
so_many_enchants-1.8.0 (1.19).jar
solapplepie-1.19.2-2.2.0.jar
sophisticatedbackpacks-1.19.2-3.18.45.819.jar
sophisticatedcore-1.19.2-0.5.54.261.jar
spirit-forge-1.19.2-2.2.6.jar
starlight-1.1.1+forge.cf5b10b.jar
StorageDrawers-1.19-11.1.2.jar
Structory_1.19.3_v1.3.1a.jar
Structory_Towers_1.19.3_v1.0.2.jar
structurize-1.19.2-1.0.689-RELEASE.jar
supermartijn642configlib-1.1.6b-forge-mc1.19.jar
supermartijn642corelib-1.1.9-forge-mc1.19.jar
tectonicbop-1.19.2-Beta3.jar
tectonic-mod-mc1.19.2-v1.1.10.jar
TerraBlender-forge-1.19.2-2.0.1.136.jar
TexelsPaintings-forge-1.19.2-6.2.0.jar
TonsOfEnchants-1.19.2-1.2.jar
ToolBelt-1.19.2-1.19.7.jar
towntalk-1.19.2-1.0.0.jar
TradingPost-v4.2.0-1.19.2-Forge.jar
twilightforest-1.19.2-4.2.1518-universal.jar
Unique Enchantments Apex-1.19.2-3.0.1.jar
Unique Enchantments Base-1.19.2-3.0.2.1.jar
Unique Enchantments Battle-1.19.2-3.0.2.jar
Unique Enchantments-1.19.2-4.0.2.1.jar
voidtotem-forge-1.19.2-2.1.0.jar
waystones-forge-1.19.2-11.4.1.jar
witchmobility-1.3.2-1.19.2.jar
YungsApi-1.19.2-Forge-3.8.9.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.0.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.0.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
YungsExtras-1.19.2-Forge-3.1.0.jar

**Comment by gisellevonbingen** [comment]
It is 'nocube's_farmers_compats_1.0.0_Forge_1.19.2.jar' 's problem.
This mod was tried to add 'knives' tag to aquaculture's knives.

![image](https://github.com/gisellevonbingen-Minecraft/MineColonies_Compatibility/assets/44163945/fe372d83-eed9-4b55-937e-0428e8198819)

Please report to Farmer's Compats' dev to that tag should be set as not required.
Or please install aquaculture mod.
